# MPC Controller Parameters
# Control parameters
control_rate: 10.0
prediction_horizon: 10

# Velocity limits
max_linear_vel: 0.5
max_angular_vel: 0.3
position_tolerance: 0.03
angle_tolerance: 0.05

# Acceleration limits
max_linear_acc: 1.5  # Maximum linear acceleration (m/s²)
max_angular_acc: 1.5  # Maximum angular acceleration (rad/s²)

# Joint configuration
joint_names:
  - torso_lift_joint
  - shoulder_pan_joint
  - shoulder_lift_joint
  - upperarm_roll_joint
  - elbow_flex_joint
  - forearm_roll_joint
  - wrist_flex_joint
  - wrist_roll_joint

max_joint_velocities: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
max_joint_accelerations: [0.01, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  # Maximum joint acceleration (rad/s²)

# MPC cost weights - State weights (x, y, theta, torso_joint, 7 arm_joints)
Q_state: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

# Control weights (base_linear, base_angular, torso_joint, 7 arm_joints)
R_control: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

# Slack weights
slack_dynamics_weight: 1000.0
slack_obstacle_weight: 200.0

# Obstacle avoidance parameters
lidar_max_range: 1.5  # Maximum range to consider for obstacle detection (meters)
safe_distance: 0.5    # Minimum safe distance from obstacles (meters)
voxel_size: 0.3       # Size of voxels for point cloud clustering (meters)
max_obstacle_points: 10  # Maximum number of obstacle points to consider
obstacle_weight: 100.0   # Weight for obstacle avoidance constraints
gamma_k: 0.1            # CBF decay rate

# Debug settings
debug: true