# MPC Controller Parameters
# Control parameters
control_rate: 20
prediction_horizon: 30
trajectory_end_threshold: 0.1 # The tolerance for reaching the final goal state

# Velocity limits
max_linear_vel: 0.5
max_angular_vel: 1.2

# Joint configuration
joint_names:
  - torso_lift_joint
  - shoulder_pan_joint
  - shoulder_lift_joint
  - upperarm_roll_joint
  - elbow_flex_joint
  - forearm_roll_joint
  - wrist_flex_joint
  - wrist_roll_joint

max_joint_velocities: [0.2, 1, 1, 1, 1, 1, 1, 1]

# MPC cost weights - State weights (x, y, theta, torso_joint, 7 arm_joints)
# Q_state: [30.0, 30.0, 20.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
Q_state: [3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1]

# Control weights (base_linear, base_angular, torso_joint, 7 arm_joints)
R_control: [1.0, 0.5, 0.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]

# Slack weights
slack_dynamics_weight: 20000.0
slack_obstacle_weight: 200.0

# Obstacle avoidance parameters
lidar_max_range: 0.5  # Maximum range to consider for obstacle detection (meters)
safe_distance: 0.15    # Minimum safe distance from obstacles (meters)
voxel_size: 0.2       # Size of voxels for point cloud clustering (meters)
max_obstacle_points: 10  # Maximum number of obstacle points to consider
gamma_k: 0.1            # CBF decay rate

# Debug settings
debug: true