#!/usr/bin/env python3

import rospy
import sys
import os

# Get the path to the src directory
script_dir = os.path.dirname(os.path.realpath(__file__))
pkg_dir = os.path.dirname(script_dir)

# Add the src directory to the Python path
sys.path.insert(0, os.path.join(pkg_dir, 'src'))

# Import and run the main script
from fetch_whole_body_controller.whole_body_controller_mpc import WholeBodyController

if __name__ == '__main__':
    try:
        controller = WholeBodyController()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass 